name: nfl_players_app
description: A new Flutter project.
# ... other metadata ...

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # ... other dependencies ...

dev_dependencies:
  flutter_lints: ^1.0.0  # Correctly indented
  flutter_test:
    sdk: flutter
  # ... other dev_dependencies ...

flutter:
  uses-material-design: true
  assets:
    - assets/player.json
